[features]
seeds = false
skip-lint = false
[programs.localnet]
roulette = "9bBoqfPybm2uKfswK8NHysk4L8sa5UzMJeMmSbxq6J5t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/hcrypto/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
