[features]
seeds = true
skip-lint = false
[programs.localnet]
roulette = "AiXuPBF1sDDthJjzdph6k43Rva2WdPW7kMjAmWxYhPNS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/hcrypto/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
